<?php


namespace Niexiawei\HyperfRabbitmqRpc\Annotation;

use Niexiawei\HyperfRabbitmqRpc\MethodHandle;
use Hyperf\Di\Annotation\AbstractAnnotation;

/**
 * Class RpcService
 * @package App\Annotation
 * @Annotation
 * @Target({"METHOD"})
 */

class RpcServer extends AbstractAnnotation
{
    public $name;

    public function collectMethod(string $className, ?string $target): void
    {

        if (!$this->name){
            $this->name = $className;
        }

        MethodHandle::$mapping[$this->name] = [$className,$target];


        parent::collectMethod($className, $target); // TODO: Change the autogenerated stub
    }
}
