<?php


namespace Niexiawei\HyperfRabbitmqRpc\Annotation;

use Niexiawei\HyperfRabbitmqRpc\MethodHandle;
use Hyperf\Di\Annotation\AbstractAnnotation;

/**
 * Class RpcService
 * @package App\Annotation
 * @Annotation
 * @Target({"METHOD"})
 */

class RpcServer extends AbstractAnnotation
{
    /**
     * @var string
     */
    public $service;

    public function collectMethod(string $className, ?string $target): void
    {

        if (!$this->service){
            $this->service = $className;
        }

        MethodHandle::$mapping[$this->service] = [$className,$target];


        parent::collectMethod($className, $target); // TODO: Change the autogenerated stub
    }
}
